[package]
name = "cvlm"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
license = "Apache 2.0"
version = "0.0.1"
published-at = "0x436572746f7261"

[dependencies]
MoveStdlib = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/move-stdlib", rev = "framework/testnet" }

[addresses]
cvlm = "0x436572746f7261"
